### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/teaching#40]
via @danielskatz:

http://www.canuck.com/famous5/html/history.html doesn't work for me - you link to it in why I teach.

**Comment by quobit** [comment]
Last available version in https://web.archive.org/web/20050413020628/http://canuck.com:80/famous5/html/history.html

**Comment by gvwilson** [comment]
Issue moved to [gvwilson/thirdbit #49](https://github.com/gvwilson/thirdbit/issues/49) via [**ZenHub**](https://www.zenhub.com/)
